import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { fonts } from '../../theme/fonts';
import { spacing } from '../../theme/typography';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFill,
  },
  gradient: {
    height: 2,
    left: 0,
    right: 0,
    position: 'absolute',
  },
  upperTab: {
    width: '70%',
    alignSelf: 'center',
    backgroundColor: colors.secondary,
    flexDirection: 'row',
    zIndex: 2,
    padding: 10,
    paddingVertical: spacing.lg,
    justifyContent: 'space-between',
    overflow: 'hidden',
    borderRadius: 8,
    paddingHorizontal: 32,
  },
  logoContainer: { alignItems: 'center', gap: 4 },
  logoText: {
    fontSize: 10,
    fontFamily: fonts.medium,
  },
  topMask: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.gray,
    opacity: 0.7,
  },
  bottomMask: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.gray,
    opacity: 0.7,
  },
  middleRow: {
    flexDirection: 'row',
    width: '100%',
    height: 260,
  },
  sideMask: {
    flex: 1,
    backgroundColor: colors.gray,
    opacity: 0.7,
  },
  scanArea: {
    width: 260,
    height: 260,
  },
  scanLine: {
    position: 'absolute',
    top: 10,
    width: '100%',
    height: 3,
    borderRadius: 3,
    opacity: 0.5,
    backgroundColor: colors.primary,
  },
  cornerBase: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderColor: colors.primary,
    borderWidth: 6,
    borderRadius: 10,
    opacity: 0.7,
  },
  cornerTopLeft: {
    position: 'absolute',
    top: -10,
    left: -10,
    zIndex: 2,
    width: 40,
    height: 40,
    borderLeftWidth: 10,
    borderTopWidth: 10,
    borderColor: colors.primary,
    borderTopLeftRadius: 10,
  },
  cornerTopRight: {
    position: 'absolute',
    top: -10,
    right: -10,
    width: 40,
    zIndex: 2,
    height: 40,
    borderRightWidth: 10,
    borderTopWidth: 10,
    borderColor: colors.primary,
    borderTopRightRadius: 10,
  },
  cornerBottomLeft: {
    position: 'absolute',
    bottom: -10,
    zIndex: 2,
    left: -10,
    width: 40,
    height: 40,
    borderLeftWidth: 10,
    borderBottomWidth: 10,
    borderColor: colors.primary,
    borderBottomLeftRadius: 10,
  },
  cornerBottomRight: {
    position: 'absolute',
    zIndex: 2,
    bottom: -10,
    right: -10,
    width: 40,
    height: 40,
    borderRightWidth: 10,
    borderBottomWidth: 10,
    borderColor: colors.primary,
    borderBottomRightRadius: 10,
  },
});

export default styles;
